apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
spec:
  selector:
    matchLabels:
      name: tetris
  template:
    metadata:
      labels:
        name: tetris
    spec:
      containers:
        - name: tetris
          image: lrakai/tetris
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tetris-service
spec:
  type: NodePort
  selector:
    name: tetris
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
